# Import

In [13]:
import _pickle
import numpy as np
import pandas as pd
from mlxtend.evaluate import bias_variance_decomp
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.ensemble import (AdaBoostClassifier, BaggingClassifier,
                              ExtraTreesClassifier, RandomForestClassifier,
                              StackingClassifier, VotingClassifier)
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (SCORERS, accuracy_score, average_precision_score,
                             confusion_matrix, make_scorer, matthews_corrcoef,
                             precision_score, recall_score, roc_auc_score)
from sklearn.model_selection import (GridSearchCV, LeaveOneOut,
                                     RandomizedSearchCV, StratifiedKFold,
                                     cross_validate)
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC, LinearSVC
from sklearn.tree import DecisionTreeClassifier

# GV and Func

In [14]:
def specificity(y_true, y_pred):
    return (2 * accuracy_score(y_true, y_pred)) - recall_score(y_true, y_pred)
    # tn, fp, fn, tp = confusion_matrix(y_true=y_true, y_pred=y_pred).ravel()
    # return tn / (tn + fp)


scoring = {
    "accuracy": make_scorer(accuracy_score),
    "mcc": make_scorer(matthews_corrcoef),
    "precision": make_scorer(precision_score),
    "specificity": make_scorer(specificity, greater_is_better=True),
    "sensitivity": make_scorer(recall_score),
    "auroc": make_scorer(roc_auc_score),
    "ap": make_scorer(average_precision_score),
}

In [15]:
clfs = {
    'DT':
    DecisionTreeClassifier(random_state=0),
    'LR':
    LogisticRegression(max_iter=10000, random_state=0),
    'RFC':
    RandomForestClassifier(random_state=0),
    'SVC(kernel = rbf)':
    SVC(kernel='rbf', random_state=0),
    'SVC(kernel = rbf, tuned)':
    SVC(kernel='rbf', C=5.44, gamma=.00237, random_state=0),
    'SVC(kernel = linear)':
    SVC(kernel='linear', random_state=0),
    'SVC(kernel = poly)':
    SVC(kernel='poly', random_state=0),
    'SVC(kernel = sigmoid)':
    SVC(kernel='sigmoid', random_state=0),
    'EXT':
    ExtraTreesClassifier(random_state=0),
    'GNB':
    GaussianNB(),
    "ADB":
    AdaBoostClassifier(random_state=0),
    "LDA":
    LinearDiscriminantAnalysis(),
    "DT":
    DecisionTreeClassifier(random_state=0),
    "KNN":
    KNeighborsClassifier(),
    'BG':
    BaggingClassifier(random_state=0),
    'BGsvmrbf':
    BaggingClassifier(base_estimator=SVC(kernel='rbf',
                                         random_state=0,
                                         probability=True),
                      random_state=0)
}

In [16]:
skf = StratifiedKFold(
    n_splits=10,
    random_state=0,
    shuffle=True)

In [17]:
def CV(X, y, model, cv=10):
    scores = cross_validate(model,
                            X,
                            y,
                            cv=cv,
                            scoring=scoring,
                            return_train_score=True,
                            return_estimator=True,
#                             verbose=1
                           )

    return {
        'ACC(%)': np.mean(scores["test_accuracy"]) * 100,
        'SN(%)': np.mean(scores["test_sensitivity"]) * 100,
        'SP(%)': np.mean(scores["test_specificity"]) * 100,
        'MCC': np.mean(scores["test_mcc"]),
    }

In [18]:
def IND(X, y, test_X, test_y, model):
    model.fit(X, y)
    pred_y = model.predict(test_X)

    return {
        'ACC(%)': accuracy_score(test_y, pred_y) * 100,
        'SE(%)': recall_score(test_y, pred_y) * 100,
        'SP(%)': specificity(test_y, pred_y) * 100,
        'MCC': matthews_corrcoef(test_y, pred_y),
    }

In [19]:
def JK(X, y, model, verbose = False):
    loo = LeaveOneOut()
    original = []
    pred = []
    i = 0
    for train_idx, test_idx in loo.split(X):
        print(i, end = '\t')
        i += 1
#         print(test_idx, end=',')
        model.fit(X[train_idx], y[train_idx])
        original.append(y[test_idx])
        pred.append(model.predict(X[test_idx]))
        
    return {
        'ACC(%)': accuracy_score(original, pred) * 100,
        'SE(%)': recall_score(original, pred) * 100,
        'SP(%)': specificity(original, pred) * 100,
        'MCC': matthews_corrcoef(original, pred),
    }

# Load data

In [20]:
file_name = '../Features/rf452.npz'

In [21]:
data = np.load(file_name)

X = data['X']
y = data['y']
test_X = data['test_X']
test_y = data['test_y']

print(X.shape, test_X.shape)

(1424, 452) (356, 452)


In [22]:
sc = StandardScaler()
X = sc.fit_transform(X)
test_X = sc.transform(test_X)

In [23]:
np.max(test_X), np.max(X), np.min(test_X), np.min(X)

(13.04237827911235, 15.95060459925624, -7.071253875525869, -9.861130594899153)

# Test

In [12]:
report_cv = []
report_ind = []

for name, clf in clfs.items():
    print(name)
    report_cv.append(CV(X, y, clf, cv= skf))
    report_cv[-1]['Classifier'] = name
    
    report_ind.append(IND(X, y, test_X, test_y, clf))
    report_ind[-1]['Classifier'] = name

DT
LR
RFC


KeyboardInterrupt: 

In [111]:
report_jk = []
name = 'SVC(kernel = rbf, tuned)'
report_jk.append(JK(X, y, clfs[name]))
report_jk[-1]['Classifier'] = name

0	1	2	3	4	5	6	7	8	9	10	11	12	13	14	15	16	17	18	19	20	21	22	23	24	25	26	27	28	29	30	31	32	33	34	35	36	37	38	39	40	41	42	43	44	45	46	47	48	49	50	51	52	53	54	55	56	57	58	59	60	61	62	63	64	65	66	67	68	69	70	71	72	73	74	75	76	77	78	79	80	81	82	83	84	85	86	87	88	89	90	91	92	93	94	95	96	97	98	99	100	101	102	103	104	105	106	107	108	109	110	111	112	113	114	115	116	117	118	119	120	121	122	123	124	125	126	127	128	129	130	131	132	133	134	135	136	137	138	139	140	141	142	143	144	145	146	147	148	149	150	151	152	153	154	155	156	157	158	159	160	161	162	163	164	165	166	167	168	169	170	171	172	173	174	175	176	177	178	179	180	181	182	183	184	185	186	187	188	189	190	191	192	193	194	195	196	197	198	199	200	201	202	203	204	205	206	207	208	209	210	211	212	213	214	215	216	217	218	219	220	221	222	223	224	225	226	227	228	229	230	231	232	233	234	235	236	237	238	239	240	241	242	243	244	245	246	247	248	249	250	251	252	253	254	255	256	257	258	259	260	261	262	263	264	265	266	267	268	269	270	271	272	273	274	275	276	27

In [117]:
clfs[name]

SVC(C=5.44, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.00237, kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [112]:
report_cv = pd.DataFrame(report_cv)
report_ind = pd.DataFrame(report_ind)
report_jk = pd.DataFrame(report_jk)

In [113]:
report_cv

ACC(%)      SN(%)      SP(%)       MCC                Classifier
0   84.266719  85.532081  83.001357  0.687357                        DT
1   88.345317  89.747653  86.942981  0.768163                        LR
2   90.030040  88.763693  91.296387  0.802483                       RFC
3   91.012509  90.451878  91.573139  0.821327         SVC(kernel = rbf)
4   91.996947  91.715571  92.278322  0.841235  SVC(kernel = rbf, tuned)
5   86.027283  87.640845  84.413720  0.722436      SVC(kernel = linear)
6   89.466660  93.683490  85.249830  0.793549        SVC(kernel = poly)
7   88.835812  89.606808  88.064817  0.778225     SVC(kernel = sigmoid)
8   90.800749  90.311033  91.290464  0.816767                       EXT
9   88.764405  89.745696  87.783113  0.777093                       GNB
10  87.220033  88.616980  85.823087  0.746259                       ADB
11  87.359894  89.327074  85.392714  0.748461                       LDA
12  89.396238  91.009390  87.783085  0.789512                       KNN
13  89.253915  86.932707  91.575123  0.787311                        BG
14  91.081454  90.729656  91.433252  0.822641                  BGsvmrbf

In [114]:
report_ind

ACC(%)      SE(%)      SP(%)       MCC                Classifier
0   80.337079  84.269663  76.404494  0.608627                        DT
1   85.955056  86.516854  85.393258  0.719147                        LR
2   88.483146  87.640449  89.325843  0.769772                       RFC
3   90.449438  87.640449  93.258427  0.810268         SVC(kernel = rbf)
4   92.134831  89.325843  94.943820  0.844030  SVC(kernel = rbf, tuned)
5   83.707865  88.202247  79.213483  0.676897      SVC(kernel = linear)
6   88.483146  92.696629  84.269663  0.772410        SVC(kernel = poly)
7   87.640449  87.078652  88.202247  0.752857     SVC(kernel = sigmoid)
8   88.764045  88.764045  88.764045  0.775281                       EXT
9   86.235955  86.516854  85.955056  0.724731                       GNB
10  86.235955  86.516854  85.955056  0.724731                       ADB
11  87.359551  83.707865  91.011236  0.749192                       LDA
12  87.921348  89.325843  86.516854  0.758726                       KNN
13  87.359551  85.955056  88.764045  0.747486                        BG
14  90.168539  87.640449  92.696629  0.804400                  BGsvmrbf

In [115]:
report_jk

ACC(%)      SE(%)      SP(%)       MCC                Classifier
0  91.502809  90.870787  92.134831  0.830123  SVC(kernel = rbf, tuned)

In [116]:
# ranked_features.to_csv('Feature_ranking_RF.csv', index = False)
# report_cv.to_csv('Report_CV_RF.csv', index = False)
# report_ind.to_csv('Report_IND_RF.csv', index=False)

# ranked_features.to_csv('Feature_ranking_' + file_name.split('.')[0] + '.csv', index = False)
report_cv.to_csv('Report_CV_' + file_name.split('.')[0] + '.csv', index = False)
report_ind.to_csv('Report_IND_' + file_name.split('.')[0] + '.csv', index=False)
report_jk.to_csv('Report_JK_' + file_name.split('.')[0] + '.csv', index=False)

# Tuning

In [55]:
# parma_dist = dict(
#     C = np.logspace(-2, 4, 10),
#     gamma = np.logspace(-9, 3, 10)
# )

# rnd = RandomizedSearchCV(clf,
#                          param_distributions=parma_dist,
#                          scoring='accuracy',
#                          cv=skf,
#                          random_state=0,
#                          n_jobs=4,
#                          verbose=1)

# rnd.fit(X, y)

In [41]:
parma_dist = dict(
    C = np.logspace(-2, 4, 10),
    gamma = np.logspace(-9, 3, 10)
)

grid = GridSearchCV(clfs['SVC(kernel = rbf)'],
                    param_grid=parma_dist,
                    cv=skf,
                    n_jobs=-1,
                    verbose=1,
                    scoring='accuracy')

grid.fit(X, y)

print(grid.best_params_, grid.best_score_, IND(X, y, test_X, test_y, grid.best_estimator_))
print(grid.param_grid)

Fitting 10 folds for each of 100 candidates, totalling 1000 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   20.1s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:  1.4min
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed:  3.1min
[Parallel(n_jobs=-1)]: Done 792 tasks      | elapsed:  5.1min
[Parallel(n_jobs=-1)]: Done 1000 out of 1000 | elapsed:  6.2min finished


GridSearchCV(cv=StratifiedKFold(n_splits=10, random_state=0, shuffle=True),
             error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=0, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=-1,
             par...,
       4.64158883e+00, 2.15443469e+01, 1.00000000e+02, 4.64158883e+02,
       2.15443469e+03, 1.00000000e+04]),
                         'gamma': array([1.00000000e-09, 2.15443469e-08, 4.64158883e-07, 1.00000000e-05,
       2.15443469e-04, 4.64158883e-03, 1.00000000e-01, 2.15443469e+00,
       4.64158883e+01, 1.00000000e+03])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy'

In [51]:
parma_dist = dict(
    C = np.linspace(1, 21, 10),
    gamma = np.linspace(0.0002, 0.01, 10)
)

grid = GridSearchCV(clfs['SVC(kernel = rbf)'],
                    param_grid=parma_dist,
                    cv=skf,
                    n_jobs=-1,
                    verbose=1,
                    scoring='accuracy')

grid.fit(X, y)

print(grid.best_params_, grid.best_score_, IND(X, y, test_X, test_y, grid.best_estimator_))
print(grid.param_grid)

Fitting 10 folds for each of 100 candidates, totalling 1000 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    8.1s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:   57.0s
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed:  2.2min
[Parallel(n_jobs=-1)]: Done 792 tasks      | elapsed:  4.0min
[Parallel(n_jobs=-1)]: Done 1000 out of 1000 | elapsed:  5.1min finished


GridSearchCV(cv=StratifiedKFold(n_splits=10, random_state=0, shuffle=True),
             error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=0, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=-1,
             param_grid={'C': array([ 1.        ,  3.22222222,  5.44444444,  7.66666667,  9.88888889,
       12.11111111, 14.33333333, 16.55555556, 18.77777778, 21.        ]),
                         'gamma': array([0.0002    , 0.00128889, 0.00237778, 0.00346667, 0.00455556,
       0.00564444, 0.00673333, 0.00782222, 0.00891111, 0.01      ])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', ve

In [56]:
# rf = rfc(random_state=0)
# parma_dist = dict(
#     n_estimators = np.linspace(1, 1000, 5, dtype = np.int),
#     min_samples_leaf = np.linspace(1, 1000, 5, dtype = np.int),
#     max_features = ['auto', 'sqrt', 'log2'],
#     oob_score = [True, False],
#     criterion = ['gini', 'entropy']
# )

# grid = GridSearchCV(rf,
#                     param_grid=parma_dist,
#                     cv=skf,
#                     n_jobs=4,
#                     verbose=1,
#                     scoring='accuracy')

# grid.fit(X, y)

# Ensemble

In [26]:
vt = VotingClassifier(estimators=[
    ('gnb', GaussianNB()),
    ('adb', AdaBoostClassifier(random_state=0)),
    ('svmrbf', SVC(C=5.44, gamma=0.00273, probability=True, random_state=0)),
    ('ext', ExtraTreesClassifier(random_state=0))
],
                      voting='hard',
                      weights=[0.3, 0.3, 0.7, 0.3])

vt.fit(X, y)

p = vt.predict(test_X)

accuracy_score(test_y, p)

0.901685393258427

In [107]:
def JKSL(X, y, verbose=False):
    original = []
    pred = []

    loo = LeaveOneOut()
    model = get_super_learner(X, folds=10)

    dummy = np.zeros((len(X[0]), 9)).T

    i = 0
    for train_idx, test_idx in loo.split(X):
        print(i, end='\t')
        i += 1
        model.fit(X[train_idx], y[train_idx])

        original.append(y[test_idx])

        test_data = np.vstack([dummy, X[test_idx]])
        #         print(test_data.shape)
        pred.append(model.predict(test_data)[-1])

    return {
        'ACC(%)': accuracy_score(original, pred) * 100,
        'SE(%)': recall_score(original, pred) * 100,
        'SP(%)': specificity(original, pred) * 100,
        'MCC': matthews_corrcoef(original, pred),
    }


In [27]:
# make a prediction with a stacking ensemble
# define the base models
level0 = list()

level0.append((
    'VC',
    VotingClassifier(
        [
            ('DT', DecisionTreeClassifier(random_state=0)),
            ('ABC', AdaBoostClassifier(random_state=0)),
            ('LDA', LinearDiscriminantAnalysis()),
            #             ('SVCL', SVC(kernel='poly', random_state=0, probability=True))
        ],
        voting='soft',
        n_jobs=-1,
        # weights=[1, 1, 1.5]
    )))s
# level0.append(('ext', ext(random_state=0)))
level0.append(('svm(rbf, tuned)',
               SVC(kernel='rbf',
                   C=5.44,
                   gamma=.00237,
                   random_state=0,
                   probability=True)))
# level0.append(('svc(poly)', SVC(kernel='poly',
#                                 random_state=0,
#                                 probability=True)))

# define meta learner model
level1 = LogisticRegression(solver='liblinear' ,random_state=0)
# level1 = SVC(kernel='linear', random_state=0)
# level1 = LinearDiscriminantAnalysis()
# define the stacking ensemble
model = StackingClassifier(estimators=level0,
                           final_estimator=level1,
                           stack_method='predict_proba',
                           cv=skf)
# fit the model on all available data
model.fit(X, y)
# make a prediction for one example
yhat = model.predict(test_X)
print('Predicted Accuracy: %f' % accuracy_score(test_y, yhat))
print('Predicted Sensitivity: %f' % recall_score(test_y, yhat))
print('Predicted Specificity: %f' % specificity(test_y, yhat))
print('Predicted MCC: %f' % matthews_corrcoef(test_y, yhat))

Predicted Accuracy: 0.926966
Predicted Sensitivity: 0.898876
Predicted Specificity: 0.955056
Predicted MCC: 0.855283


In [28]:
print('10-Fold CV')
print(CV(X, y, model, StratifiedKFold(n_splits=10, shuffle=True, random_state=0)))

{'ACC(%)': 91.85560917955286,
 'SN(%)': 91.71557120500783,
 'SP(%)': 91.99564715409785,
 'MCC': 0.838222242390561}

In [108]:
model

SVC(C=5.44, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.00237, kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
print('JK')
JKSL(X, y, model)


In [106]:
model = clfs['SVC(kernel = rbf, tuned)']
mse, bias, var = bias_variance_decomp(model,
                                         X,
                                         y,
                                         test_X,
                                         test_y,
                                         loss='mse',
                                         random_seed=0)
print('Mean Square Error: ', mse)
print('Bias : ', bias)
print('Variance : ', var)

loss, bias, var = bias_variance_decomp(model, X, y, test_X, test_y, loss='0-1_loss', random_seed=0)
print('0-1 loss: ', loss)
print('Bias : ', bias)
print('Variance : ', var)

Mean Square Error:  0.08980337078651686
Bias :  0.07276573033707866
Variance :  0.017037640449438205
0-1 loss:  0.08980337078651686
Bias :  0.08426966292134831
Variance :  0.02308988764044944


In [66]:
clf.intercept_

array([-0.00476928])

In [69]:
clf.support_, len(clf.support_)

(array([712, 713, 714, ..., 709, 710, 711], dtype=int32), 1424)

In [60]:
clf.support_vectors_.

(1424, 452)

In [61]:
clf.n_support_

array([712, 712], dtype=int32)

In [65]:
clf.dual_coef_[0]

array([-0.90736518, -1.00116209, -0.99200458, ...,  0.997675  ,
        0.98595197,  0.96508171])

In [ ]:
tell brinto to run JK
Update the accuracy table